---
# tasks file for ansible-role-system
- name: Allow sudo without password
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
    insertafter: '^%admin\tALL=\(ALL\) ALL'
    validate: "visudo -cf %s"
  when: sudo_without_password|default(false) == true

- name: Ensures /etc/keyd/ exists
  become: yes
  file:
    path: /etc/keyd
    state: directory
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install keyd-git
  aur:
    name: keyd-git
    use: auto
    state: present
  become: yes
  become_user: "{{ ansible_user_id }}"
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start keyd service
  service:
    name: keyd
    state: started
    enabled: yes
  when: ansible_facts["distribution"] == "Archlinux"

- name: Copy keyd config file
  become: yes
  copy:
    src: "keyd_default.conf"
    dest: /etc/keyd/default.conf
    owner: root
    group: root
  notify:
    - reload systemd config
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install hdparm
  become: yes
  pacman:
    name: hdparm
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

- name: Enable and start weekly filesystem TRIM timer
  service:
    name: fstrim.timer
    enabled: yes
  when: ansible_facts["distribution"] == "Archlinux"

- name: Copy udev rule for ergodox keyboard
  become: yes
  copy:
    src: "{{ role_path }}/files/50-wally.rules"
    dest: /etc/udev/rules.d/50-wally.rules
    owner: root
    group: root
  when: ergodox_keyboard|default(false) == true

- name: Add plugdev group
  become: yes
  group:
    name: plugdev
    state: present

- name: adding existing "{{ ansible_user_id }}" to group plugdev
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: ["plugdev"]
    append: yes

- include_tasks: thinkpad.yml
  when: thinkpad|default(false) == true

- include_tasks: hosts.yml
  when: hosts_pack|default(false) != "none"
